title: Talvez não existam ninjas na programação. Mas podemos ser Quase Ninjas.
description: > # this means to ignore newlines until "baseurl:"
  Produzindo bugs desde 2003.
  Aqui eu escrevo sobre tecnologia, sobre desenvolvimento de software
  e sobre meus pensamentos mais aleatórios.
  Meu nome é Thiago Ramos e eu desenvolvo software há um bom tempo, sempre aprendendo
  e tentando ser melhor hoje do que eu fui ontem.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.quaseninja.com.br" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: "http://twitter.com/thramosal"

# Author Settings
author: Thiago Ramos # add your name
author-img: thiago-ramos.jpg # add your photo
about-author: Produzindo bugs desde 2003. # add description
social-twitter: thramosal
social-facebook: thiagoramosal
social-github: thiagoramos23 # add your Github handle
social-linkedin: thiagoramosal
social-email: thiagoramos.al@gmail.com
organization: Quase Ninja

# Disqus
discus-identifier: quaseninja # add your discus identifier

# Tracker
analytics: UA-55550920-2

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
